FROM alpine:3.8

# common environment variables

ENV KATALON_ROOT_DIR=/katalon
ENV KATALON_KATALON_ROOT_DIR=$KATALON_ROOT_DIR/katalon
ENV KATALON_MAKE_EXECUTABLE_SCRIPT=$KATALON_KATALON_ROOT_DIR/make_executable.sh
ENV KATALON_CLEAN_UP_SCRIPT=$KATALON_KATALON_ROOT_DIR/cleanup.sh
ENV KATALON_VERSION_FILE=/katalon/version
ENV KATALON_KATALON_INSTALL_DIR_PARENT=/opt
ENV KATALON_KATALON_INSTALL_DIR=$KATALON_KATALON_INSTALL_DIR_PARENT/katalonstudio

# bash
RUN /bin/sh -c "apk add --no-cache bash"

## katalon
RUN mkdir -p $KATALON_KATALON_ROOT_DIR
WORKDIR $KATALON_KATALON_ROOT_DIR
ADD ./src ./

# build
RUN chmod a+x $KATALON_MAKE_EXECUTABLE_SCRIPT
RUN $KATALON_MAKE_EXECUTABLE_SCRIPT .

RUN ./index.sh
RUN $KATALON_CLEAN_UP_SCRIPT

WORKDIR /

ENTRYPOINT cat $KATALON_VERSION_FILE && $KATALON_KATALON_ROOT_DIR/scripts/katalon-execute.sh